name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Build
      run: dotnet build OTDPlugins/AdvancedAntiSmoothingFilter/AdvancedAntiSmoothingFilter.csproj --configuration Release
    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        path: OTDPlugins/AdvancedAntiSmoothingFilter/bin/Release/netcoreapp3.1/AdvancedAntiSmoothingFilter.dll
