name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Build (NET Core 3.1)
      run: |
        dotnet publish AdvancedAntiSmoothingFilter/AdvancedAntiSmoothingFilter.csproj --configuration Release --framework netcoreapp3.1 -o ./build/netcoreapp3.1/AASF
        dotnet publish ExperimentalASFilter/ExperimentalASFilter.csproj --configuration Release --framework netcoreapp3.1 -o ./build/netcoreapp3.1/EASF
        dotnet publish OemKill/OemKill.csproj --configuration Release --framework netcoreapp3.1 -o ./build/netcoreapp3.1/OemKill
    - name: Setup .NET 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100-preview.7.20366.6
    - name: Build (NET 5.0)
      run: |
        dotnet publish AdvancedAntiSmoothingFilter/AdvancedAntiSmoothingFilter.csproj --configuration Release --framework net5.0 -o ./build/net5.0/AASF
        dotnet publish ExperimentalASFilter/ExperimentalASFilter.csproj --configuration Release --framework net5.0 -o ./build/net5.0/EASF
        dotnet publish OemKill/OemKill.csproj --configuration Release --framework net5.0 -o ./build/net5.0/OemKill
    - name: Upload AASF (NET Core 3.1)
      uses: actions/upload-artifact@main
      with:
        name: Advanced-AntiSmoothing-Filter (NET Core 3.1)
        path: |
          ./build/netcoreapp3.1/AASF/*.dll
          !./build/netcoreapp3.1/AASF/*.json
          !./build/netcoreapp3.1/AASF/TabletDriverPlugin.dll
    - name: Upload AASF (NET 5.0)
      uses: actions/upload-artifact@main
      with:
        name: Advanced-AntiSmoothing-Filter (NET 5.0)
        path: |
          ./build/net5.0/AASF/*.dll
          !./build/net5.0/AASF/*.json
          !./build/net5.0/AASF/TabletDriverPlugin.dll
    - name: Upload EASF (NET Core 3.1)
      uses: actions/upload-artifact@main
      with:
        name: ExperimentalASFilter (NET Core 3.1)
        path: |
          ./build/netcoreapp3.1/EASF/*.dll
          !./build/netcoreapp3.1/EASF/*.json
          !./build/netcoreapp3.1/EASF/TabletDriverPlugin.dll
    - name: Upload EASF (NET 5.0)
      uses: actions/upload-artifact@main
      with:
        name: ExperimentalASFilter (NET 5.0)
        path: |
          ./build/net5.0/EASF/*.dll
          !./build/net5.0/EASF/*.json
          !./build/net5.0/EASF/TabletDriverPlugin.dll
    - name: Upload OemKill (NET Core 3.1)
      uses: actions/upload-artifact@main
      with:
        name: OemKill (NET Core 3.1)
        path: |
          ./build/netcoreapp3.1/OemKill/*.dll
          !./build/netcoreapp3.1/OemKill/*.json
          !./build/netcoreapp3.1/OemKill/TabletDriverPlugin.dll
    - name: Upload OemKill (NET 5.0)
      uses: actions/upload-artifact@main
      with:
        name: OemKill (NET 5.0)
        path: |
          ./build/net5.0/OemKill/*.dll
          !./build/net5.0/OemKill/*.json
          !./build/net5.0/OemKill/TabletDriverPlugin.dll
