name: .NET Core

on: [push, pull_request, workflow_dispatch]

jobs:
       
  build:
    strategy:
      matrix:
        plugin: [MLFilter, OemKill, TouchEmu, WindowsInk, VMultiMode]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive
      
    - name: Setup ${{ matrix.net }}
      uses: actions/setup-dotnet@v1.7.0
        
    - name: Build
      env:
        plugin: ${{ matrix.plugin }}
      run: dotnet publish $plugin --configuration Release --framework netcoreapp3.1 -o ./build/netcoreapp3.1/$plugin
      
    - name: Upload ${{ matrix.plugin }}
      uses: actions/upload-artifact@main
      with:
        name: ${{ matrix.plugin }}
        path: |
          ./build/netcoreapp3.1/${{ matrix.plugin }}/*.dll
          !./build/netcoreapp3.1/${{ matrix.plugin }}/*.json
          !./build/netcoreapp3.1/${{ matrix.plugin }}/*.pdb
          !./build/netcoreapp3.1/${{ matrix.plugin }}/OpenTabletDriver.Plugin.dll
          !./build/netcoreapp3.1/${{ matrix.plugin }}/Newtonsoft.Json.dll
