name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    branches: [ master ]

jobs:
       
  build:
    strategy:
      matrix:
        plugin: [AdvancedAntiSmoothingFilter, ExperimentalASFilter, OemKill]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup ${{ matrix.net }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Build
      run: dotnet publish $plugin --configuration Release --framework netcoreapp3.1 -o ./build/netcoreapp3.1/$plugin
      
    - name: Upload ${{ matrix.plugin }}
      uses: actions/upload-artifact@main
      with:
        name: ${{ matrix.plugin }}
        path: |
          ./build/netcoreapp3.1/${{ matrix.plugin }}/*.dll
          !./build/netcoreapp3.1/${{ matrix.plugin }}/*.json
          !./build/netcoreapp3.1/${{ matrix.plugin }}/TabletDriverPlugin.dll
          
      env:
        plugin: ${{ matrix.plugin }}
