name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Build (NET Core 3.1)
      run: |
        dotnet build AdvancedAntiSmoothingFilter/AdvancedAntiSmoothingFilter.csproj --configuration Release --framework netcoreapp3.1 -o ./build/netcoreapp3.1
        dotnet build ExperimentalASFilter/ExperimentalASFilter.csproj --configuration Release --framework netcoreapp3.1 -o ./build/netcoreapp3.1
    - name: Setup .NET 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100-preview.7.20366.6
    - name: Build (NET 5.0)
      run: |
        dotnet build AdvancedAntiSmoothingFilter/AdvancedAntiSmoothingFilter.csproj --configuration Release --framework net5.0 -o ./build/net5.0
        dotnet build ExperimentalASFilter/ExperimentalASFilter.csproj --configuration Release --framework net5.0 -o ./build/net5.0
    - name: Upload NET Core 3.1 artifact
      uses: actions/upload-artifact@master
      with:
        name: OTDPlugins (NET Core 3.1)
        path: ./build/netcoreapp3.1/*.dll
    - name: Upload NET 5.0 artifact
      uses: actions/upload-artifact@master
      with:
        name: OTDPlugins (NET 5.0)
        path: ./build/net5.0/*.dll
