name: .NET Core

on: [push, pull_request, workflow_dispatch]

jobs:

  build:
    strategy:
      matrix:
        plugin: [MeL, OemKill, TouchEmu, WindowsInk, VMultiMode, PrecisionControl, ScriptRunner]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive

    - name: Setup ${{ matrix.net }}
      uses: actions/setup-dotnet@main
      with:
        dotnet-version: '5.0.100'

    - name: Build
      env:
        plugin: ${{ matrix.plugin }}
      run: dotnet publish $plugin --configuration Release --framework net5 -o ./build/$plugin

    - name: Upload ${{ matrix.plugin }}
      uses: actions/upload-artifact@main
      with:
        name: ${{ matrix.plugin }}
        path: |
          ./build/${{ matrix.plugin }}/*.dll
          !./build/${{ matrix.plugin }}/*.json
          !./build/${{ matrix.plugin }}/*.pdb
          !./build/${{ matrix.plugin }}/OpenTabletDriver.Plugin.dll
          !./build/${{ matrix.plugin }}/Newtonsoft.Json.dll
          !./build/${{ matrix.plugin }}/HidSharpCore.dll
