name: .NET Core

on: [push, pull_request, workflow_dispatch]

jobs:

  build:
    strategy:
      matrix:
        include:
          - plugin: Binding/ScriptRunner
          - plugin: Filter/MeL 
          - plugin: Filter/PrecisionControl
          - plugin: Filter/Reconstructor
          - plugin: OutputMode/TouchEmu
          - plugin: OutputMode/VMultiMode
          - plugin: OutputMode/WindowsInk
          - plugin: Tool/OemKill

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive

    - name: Setup NET 5
      uses: actions/setup-dotnet@main
      with:
        dotnet-version: '5.0.100'

    - name: Build
      env:
        plugin: ${{ matrix.plugin }}
      run: dotnet publish $plugin --configuration Release --framework net5 -o ./build/$plugin

    - name: Upload ${{ matrix.plugin }}
      uses: actions/upload-artifact@main
      with:
        name: ${{ matrix.plugin }}
        path: |
          ./build/${{ matrix.plugin }}/*.dll
          !./build/${{ matrix.plugin }}/*.json
          !./build/${{ matrix.plugin }}/*.pdb
          !./build/${{ matrix.plugin }}/OpenTabletDriver.Plugin.dll
          !./build/${{ matrix.plugin }}/Newtonsoft.Json.dll
          !./build/${{ matrix.plugin }}/HidSharpCore.dll
